const CREATE_SOCKET = 'CREATE_SOCKET';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export { CREATE_SOCKET, SIGN_IN, SIGN_OUT, SIGN_IN_FAILURE };
