const CREATE_SOCKET = 'CREATE_SOCKET';
const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export { CREATE_SOCKET, SIGN_IN, SIGN_UP, SIGN_OUT, SIGN_IN_FAILURE, SIGN_UP_FAILURE };
