const CREATE_SOCKET = 'CREATE_SOCKET';
const DESTROY_SOCKET = 'DESTROY_SOCKET';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
const LOAD = 'LOAD';
const ADD_ROOM = 'ADD_ROOM';
const ADD_MESSAGE = 'ADD_MESSAGE';
const CHANGE_ROOM = 'CHANGE_ROOM';
const REMOVE_ROOM = 'REMOVE_ROOM';
const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export {
  CREATE_SOCKET,
  DESTROY_SOCKET,
  SIGN_IN,
  SIGN_OUT,
  SIGN_IN_FAILURE,
  LOAD,
  ADD_ROOM,
  ADD_MESSAGE,
  CHANGE_ROOM,
  REMOVE_ROOM,
  ADD_NOTIFICATION,
  REMOVE_NOTIFICATION,
};
